# Generated by Django 5.0.6 on 2024-12-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название продукта')),
                ('product_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип продукта')),
                ('category', models.CharField(blank=True, max_length=128, null=True, verbose_name='Категория продукта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Изображение продукта')),
                ('fix_price', models.FloatField(blank=True, null=True, verbose_name='Фиксированная цена за кг продукта')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Остаток продукта в кг')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
