# Generated by Django 5.0.6 on 2024-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название продукта')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение продукта')),
                ('fix_price', models.FloatField(verbose_name='Фиксированная цена за кг продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
