# Generated by Django 5.0.6 on 2024-07-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Вес продукта')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость продукта')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='catalog.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
